myspecialway/my-special-way-portal

- scripts/docker
> 🚑 hotfixing build on master

- src/app/pages/class/__snapshots__/class.component.spec.ts.snap
- src/app/pages/class/class.component.html
- src/app/pages/class/dialogs/delete/delete-class.dialog.html
- src/app/pages/student/__snapshots__/student.component.spec.ts.snap
- src/app/pages/student/student.component.html
- src/app/pages/user/__snapshots__/user.component.spec.ts.snap
- src/app/pages/user/user.component.html
- src/assets/scss/core/variables/_colors.scss
- src/assets/scss/msw-table.scss
- Hover effect on rows
- Remove Icon
- Table Toolbox(Header) Layout fix.
> [UI] Table Enhancements.

- src/app/models/lesson.model.ts
- src/app/models/point.model.ts
- src/app/models/room.model.ts
- src/index.html
nothing fancy. just added few interfaces
> #41 create lesson schema

- angular.json
- docker-compose.yml
- package.json
- scripts/test
- tests/login.e2e.ts
- tests/seed/seed.js
usage:
yarn start:local
closes #120
> #120 configuration for local env

- .dockerignore
- Dockerfile
- scripts/default-nginx.conf
> ✨ added html5 support for nginx

- src/app/pages/login/login.component.html
- src/app/pages/login/login.component.ts
- src/app/pages/pages.module.ts
I guess this is a bug, 
please notify me if there's a different requirement
issue #225
> Login page: Credentials  now changed to required

- src/app/pages/user/dialogs/update/update-user.dialog.html
Enter key fixed to submit the form instead of clearing the text input field.
Workaround added for HTML forms natural behaviour to press first form button on Enter key press
#190
> User details update form: 

- src/app/pages/user/dialogs/update/update-user.dialog.html
- src/app/pages/user/dialogs/update/update-user.dialog.ts
Users screen - Validations messages don't appear near all fields as required
> #185 validations messages dont appear

- src/app/pages/login/login.component.html
- tests/login.e2e.ts
- tests/navbar.e2e.ts
- tests/pageobjects/login.po.ts
> added some login tests.

- src/app/components/schedule/schedule.component.ts
- src/app/models/student.model.ts
- src/app/pages/student/details/tabs/student-details-hours/student-details-hours.component.ts
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
- src/app/pages/student/services/student.graphql.service.ts
- src/app/pages/student/services/student.service.ts
**IMPORTNAT**
this fix is dependant upon server PR 85 on MSW [server](https://github.com/myspecialway/my-special-way-server/pull/85
)
This PR makes sure the schedule is reflected in the schedule UI correctly.
Another bug is also being fixed here - referencing class._id instead of class_id, as it saved on users documents.
This fix closes #254 and closes #247
> Bugfix/student schedule is not saved #254

- scripts/test
- src/app/pages/class-details/class-details.view/__snapshots__/class-details.view.component.spec.ts.snap
- src/app/pages/class-details/class-details.view/class-details.view.component.html
- src/app/pages/class/class.component.html
- src/app/pages/class/dialogs/delete/delete-class.dialog.html
- tests/classes.e2e.ts
- tests/new-class.e2e.ts
- tests/pageobjects/class-details.po.ts
- tests/pageobjects/classes.po.ts
- tests/pageobjects/navbar.po.ts
- tests/pageobjects/students.po.ts
- tests/student-schedule.e2e.ts
> #236 new class e2e tests + #233 classes screen e2e tests

- .travis.yml
- scripts/k8s/config
- scripts/k8s/deploy
- scripts/k8s/init
Config kubectl to use the new cluster
> [DevOps] Config kubectl to use the new cluster

- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
It's only for the students. That's the request of Leorra
> add/update student username - must contains at least 5 hebrew letters

- src/app/app.routing.ts
- src/app/models/point.model.ts
- src/app/pages/maps/maps.container/__snapshots__/map.container.component.spec.ts.snap
- src/app/pages/maps/maps.container/map.container.component.spec.ts
- src/app/pages/maps/maps.container/map.container.component.ts
- src/app/pages/maps/maps.view/__snapshots__/map.view.component.spec.ts.snap
- src/app/pages/maps/maps.view/map.view.component.html
- src/app/pages/maps/maps.view/map.view.component.scss
- src/app/pages/maps/maps.view/map.view.component.spec.ts
- src/app/pages/maps/maps.view/map.view.component.ts
- src/app/pages/pages.module.ts
> #276 maps page show the map nodes as a list

- src/app/models/location.model.ts
- src/app/pages/maps/maps.container/map.container.component.ts
- src/app/pages/maps/maps.view/__snapshots__/map.view.component.spec.ts.snap
- src/app/pages/maps/maps.view/map.view.component.html
- src/app/pages/maps/maps.view/map.view.component.scss
- src/app/pages/maps/maps.view/map.view.component.spec.ts
- src/app/pages/maps/maps.view/map.view.component.ts
- src/app/services/location/location.graphql.service.ts
> #294 locations edit

- src/app/pages/class-details/class-details.view/__snapshots__/class-details.view.component.spec.ts.snap
- src/app/pages/class-details/class-details.view/class-details.view.component.html
- src/app/pages/class/services/class.graphql.service.ts
- src/app/pages/class/services/class.graphql.ts
> Bugfix/saved class schedule is shown in students but not in class schedule #284

- src/app/pages/user/user.component.ts
> 286 -Users page should not show students

- package.json
> Added tslint to pre-push hook

- src/app/app.module.ts
- src/app/pages/class/services/class.graphql.service.ts
- src/app/pages/class/services/class.graphql.ts
- src/app/pages/lesson/__snapshots__/lesson.component.spec.ts.snap
- src/app/pages/lesson/dialogs/cant-delete/cant-delete-lesson.dialog.html
- src/app/pages/lesson/dialogs/cant-delete/cant-delete-lesson.dialog.scss
- src/app/pages/lesson/dialogs/cant-delete/cant-delete-lesson.dialog.ts
- src/app/pages/lesson/dialogs/delete/delete-lesson.dialog.html
- src/app/pages/lesson/dialogs/delete/delete-lesson.dialog.scss
- src/app/pages/lesson/dialogs/delete/delete-lesson.dialog.ts
- src/app/pages/lesson/lesson.component.html
- src/app/pages/lesson/lesson.component.spec.ts
- src/app/pages/lesson/lesson.component.ts
- src/app/services/lesson/lesson.graphql.service.ts
- yarn.lock
closes #135.]
implement delete for lessons, related to #63
> #135 delete lesson

- src/app/pages/student/dialogs/delete/delete-student.dialog.html
- src/app/pages/student/student.component.html
- src/app/pages/student/student.component.spec.ts
- src/app/pages/student/student.component.ts
- yarn.lock
> #341 fix  student dialog titles

- src/app/pages/student/details/__snapshots__/student-details.component.spec.ts.snap
- src/app/pages/student/details/student-details.component.html
- src/app/pages/student/details/student-details.component.scss
- src/app/pages/student/details/student-details.component.spec.ts
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.scss
> #342 fix back to all students font weight

- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
> #334_add_paasowrd_validation_on_edit_student

- src/app/pages/pages.module.ts
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
> #335_show_hide_password_icon

- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
return the functionality  (was removed from master by git conflict resolving probably)
fixes #335
> fixes #335

- src/app/pages/class-details/class-details.view/__snapshots__/class-details.view.component.spec.ts.snap
- src/app/pages/class-details/class-details.view/class-details.view.component.html
- src/app/pages/class-details/class-details.view/class-details.view.component.scss
Adding a new class with the correct design
> #347 bug fix backlink to all classes

- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
> #333_remove_validation_for_hebrew_characters_only

- src/app/pages/class/class.component.html
- src/app/pages/class/class.component.ts
- src/app/pages/lesson/lesson.component.ts
- src/app/pages/student/__snapshots__/student.component.spec.ts.snap
- src/app/pages/student/student.component.html
- src/app/pages/student/student.component.spec.ts
- src/app/pages/student/student.component.ts
- src/app/pages/user/__snapshots__/user.component.spec.ts.snap
- src/app/pages/user/user.component.html
- src/app/pages/user/user.component.spec.ts
- src/app/pages/user/user.component.ts
> #321 fix sorting for students and users

- src/app/components/navbar/navbar.component.html
- src/app/components/navbar/navbar.component.scss
> fix_logout_text_and_icon

- src/app/directives/unique-username-validator.directive.ts
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
- src/app/pages/user/dialogs/base/user-details-form/__snapshots__/user-details-form.spec.ts.snap
- src/app/pages/user/dialogs/base/user-details-form/user-details-form.html
- src/app/pages/user/dialogs/base/user-details-form/user-details-form.spec.ts
- src/app/pages/user/dialogs/base/user-details-form/user-details-form.ts
- src/app/services/authentication/authentication.service.ts
- src/app/validators/UniqueUsernameValidator.ts
> #318 add username validation on user management

- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
> #426 New student gets wrong User or password assigned as default

- src/app/pages/student/services/student.service.ts
Fetching all the classes data after deleting a student.
closes #275
> #275 - bugfix/Cannot delete a class with no students

- src/app/file-import/students-file-import/students-file-import.service.ts
Logs was added to give more info for the validation error.
> add_error_logs_to_import_student_file_validations

- src/app/pages/maps/maps.view/map.view.component.scss
> #486_Maps-when_show_map_of_floor_2_cannot_select_floor_-1

- src/app/services/lesson/lesson.graphql.service.ts
updated or deleted.
This closes #523
> #523 - Fetching all classes and all students after a lesson has been

- src/app/pages/user/dialogs/base/user-details-form/user-details-form.ts
> #521 - Classes are sorted in user-details dialogue box

- README.md
- simple-setup.md
Reviewer/Co-author: Itay Sidis
> [000000] Adding simple instructions to environments setup.

- src/assets/scss/core/_footers.scss
> #471 - Footer is displayed according to content.

- src/app/pages/firstlogin/firstlogin.component.html
- src/app/pages/firstlogin/firstlogin.component.scss
- src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.scss
- src/app/pages/login/login.component.html
- src/app/pages/maps/maps.container/maps.container.html
- src/app/pages/maps/maps.container/maps.container.scss
- src/app/pages/shared/session-mgmt/session-footer/session-footer.component.html
- src/app/pages/shared/session-mgmt/session-footer/session-footer.component.scss
- src/app/pages/shared/session-mgmt/session-header/session-header.component.html
- src/app/pages/shared/session-mgmt/session-header/session-header.component.scss
first-login UI cosmetic updates
> first-login UI updates

- src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.html
- src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.scss
Change the color of error message to red.
Change the color of disabled submit button to grey.
> Fix add/edit lesson error indications

- src/app/pages/reset-password/__snapshots__/reset-password.component.spec.ts.snap
- src/app/pages/reset-password/reset-password.component.html
- src/app/pages/reset-password/reset-password.component.scss
- src/app/pages/reset-password/reset-password.component.ts
- src/environments/environment.local.ts
Add the 'email' validator to the email input.
Add validation errors for empty field and for invalid email.
Make the submit button disabled until the form is successfully validated.
> Frogot password email validation

- src/app/pages/lesson/dialogs/new-edit/edit-lesson.dialog.html
No limit of data string length in lesson name
field, cause visibility problems
> [#605] BugFix: No limit of data string length in field

- src/environments/environment.ts
> fix login issue

- src/app/components/schedule/schedule-dialog/schedule-dialog.html
- src/app/components/schedule/schedule-dialog/schedule-dialog.scss
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.html
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.spec.ts
- src/app/pages/student/details/tabs/student-details-personal-info/student-details-personal-info.component.ts
- src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.html
- src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.ts
Fixes for two bugs:
#660 
#656 
#659
> Various fixes

- schema.graphql
- scripts/test
A fix for the "Forgot Password" on the main login page
> Lessons icons

- src/app/pages/sent-successfully/sent-successfully.component.html
- src/app/pages/sent-successfully/sent-successfully.component.scss
Some UI changes to hide the NULL navbar
> Updates to sent successfully UI

- src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.html
- src/app/pages/student/dialogs/reminders/add/add-student-reminder.dialog.ts
Added support for the ability to define reminders (medicine and toilets) at any time without limiting the minutes to be a multiple of 30 min.
This is critical according to the school stuff and it is also a bug (#579)
> added support for accurate reminder time
